import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

import {
  OPENCLAW_DNS_RESOLVER_IP,
  OPENCLAW_FIREWALL_RULES_PATH,
  OPENCLAW_FIREWALL_TABLE,
  OPENCLAW_FIREWALL_UNIT_NAME,
  OPENCLAW_FIREWALL_UNIT_PATH,
  OPENCLAW_NETWORK_SUBNET
} from "./constants";
import { loadProfile } from "./profile-loader";

function requireLinuxRoot(command: string): void {
  if (process.platform !== "linux") {
    throw new Error(`${command} is supported on Linux hosts only.`);
  }

  if (typeof process.getuid === "function" && process.getuid() !== 0) {
    throw new Error(`${command} requires root privileges. Re-run with sudo.`);
  }
}

function runCommand(bin: string, args: string[], failMessage: string): void {
  const result = spawnSync(bin, args, { stdio: "inherit" });

  if (result.error) {
    throw new Error(`${failMessage}: ${result.error.message}`);
  }

  if (result.status !== 0) {
    throw new Error(`${failMessage} (exit code ${result.status ?? "unknown"})`);
  }
}

function runCommandAllowFailure(bin: string, args: string[]): void {
  spawnSync(bin, args, { stdio: "inherit" });
}

function nftTableExists(): boolean {
  const result = spawnSync("nft", ["list", "table", "inet", OPENCLAW_FIREWALL_TABLE], { stdio: "ignore" });
  return result.status === 0;
}

function buildFirewallRules(profileName: string): string {
  return `# Generated by ocs apply-firewall --profile ${profileName}
table inet ${OPENCLAW_FIREWALL_TABLE} {
  chain forward {
    type filter hook forward priority 100; policy accept;

    ct state established,related accept
    ip saddr ${OPENCLAW_NETWORK_SUBNET} ip daddr ${OPENCLAW_DNS_RESOLVER_IP} udp dport 53 accept
    ip saddr ${OPENCLAW_NETWORK_SUBNET} ip daddr ${OPENCLAW_DNS_RESOLVER_IP} tcp dport 53 accept

    # Permit dns_allowlist container to resolve upstream DNS.
    ip saddr ${OPENCLAW_DNS_RESOLVER_IP} udp dport 53 accept
    ip saddr ${OPENCLAW_DNS_RESOLVER_IP} tcp dport 53 accept

    # Practical v1 allowance: HTTPS egress; DNS allowlist constrains resolvable destinations.
    ip saddr ${OPENCLAW_NETWORK_SUBNET} tcp dport 443 accept

    # deny-by-default for remaining container egress on openclaw_net
    ip saddr ${OPENCLAW_NETWORK_SUBNET} reject with icmpx type admin-prohibited
  }
}
`;
}

function buildSystemdUnit(): string {
  return `[Unit]
Description=OpenClaw secure nftables firewall
After=network-online.target docker.service
Wants=network-online.target docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=-/usr/sbin/nft delete table inet ${OPENCLAW_FIREWALL_TABLE}
ExecStart=/usr/sbin/nft -f ${OPENCLAW_FIREWALL_RULES_PATH}
ExecStop=-/usr/sbin/nft delete table inet ${OPENCLAW_FIREWALL_TABLE}

[Install]
WantedBy=multi-user.target
`;
}

function hasSystemctl(): boolean {
  const result = spawnSync("systemctl", ["--version"], { stdio: "ignore" });
  return result.status === 0;
}

export function applyFirewall(profileName: string): void {
  requireLinuxRoot("apply-firewall");
  loadProfile(profileName);

  fs.mkdirSync(path.dirname(OPENCLAW_FIREWALL_RULES_PATH), { recursive: true });
  fs.writeFileSync(OPENCLAW_FIREWALL_RULES_PATH, buildFirewallRules(profileName), "utf8");
  fs.writeFileSync(OPENCLAW_FIREWALL_UNIT_PATH, buildSystemdUnit(), "utf8");

  if (nftTableExists()) {
    runCommand(
      "nft",
      ["delete", "table", "inet", OPENCLAW_FIREWALL_TABLE],
      "Failed to clear existing nftables table"
    );
  }

  runCommand("nft", ["-f", OPENCLAW_FIREWALL_RULES_PATH], "Failed to apply nftables rules");

  if (hasSystemctl()) {
    runCommand("systemctl", ["daemon-reload"], "Failed to reload systemd");
    runCommand(
      "systemctl",
      ["enable", "--now", OPENCLAW_FIREWALL_UNIT_NAME],
      "Failed to enable/start firewall service"
    );
  } else {
    console.warn("systemctl not available; skipping service enablement.");
  }

  console.log(`Applied firewall table '${OPENCLAW_FIREWALL_TABLE}' using profile '${profileName}'.`);
  console.log(`Rules file: ${OPENCLAW_FIREWALL_RULES_PATH}`);
  console.log(`Systemd unit: ${OPENCLAW_FIREWALL_UNIT_PATH}`);
}

export function rollbackFirewall(): void {
  requireLinuxRoot("rollback-firewall");

  if (hasSystemctl()) {
    runCommandAllowFailure("systemctl", ["disable", "--now", OPENCLAW_FIREWALL_UNIT_NAME]);
    runCommandAllowFailure("systemctl", ["daemon-reload"]);
  }

  if (nftTableExists()) {
    runCommand(
      "nft",
      ["delete", "table", "inet", OPENCLAW_FIREWALL_TABLE],
      "Failed to remove nftables table"
    );
  }

  console.log(`Rolled back firewall table '${OPENCLAW_FIREWALL_TABLE}'.`);
}
