import fs from "node:fs";
import path from "node:path";
import YAML from "yaml";

import { ProfileConfig } from "./profile-schema";

const OPENCLAW_DNS_RESOLVER_IP = "172.29.0.53";
const OPENCLAW_NETWORK_SUBNET = "172.29.0.0/24";
const DNS_UPSTREAM_SERVERS = ["1.1.1.1", "8.8.8.8"];

function normalizedAllowlist(profile: ProfileConfig): string[] {
  return [...new Set(profile.network.allow.map((domain) => domain.toLowerCase()))];
}

function buildDnsmasqConfig(profile: ProfileConfig): string {
  const allowlist = normalizedAllowlist(profile);
  const lines = [
    "# Generated by ocs install. Do not edit manually.",
    "port=53",
    "no-resolv",
    "no-hosts",
    "domain-needed",
    "bogus-priv",
    "bind-interfaces",
    "listen-address=0.0.0.0",
    "cache-size=0"
  ];

  for (const domain of allowlist) {
    for (const upstream of DNS_UPSTREAM_SERVERS) {
      lines.push(`server=/${domain}/${upstream}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

function buildCompose(profileName: string, profile: ProfileConfig): string {
  const dnsAllowlistService = {
    image: "alpine:3.20",
    restart: "unless-stopped",
    command: [
      "sh",
      "-ec",
      "apk add --no-cache dnsmasq >/dev/null && exec dnsmasq --keep-in-foreground --conf-file=/etc/dnsmasq.conf --log-facility=-"
    ],
    volumes: ["./dnsmasq.conf:/etc/dnsmasq.conf:ro"],
    networks: {
      openclaw_net: {
        ipv4_address: OPENCLAW_DNS_RESOLVER_IP
      }
    }
  };

  const openclawService: Record<string, unknown> = {
    image: "busybox:1.36",
    restart: "unless-stopped",
    command: ["sh", "-c", "while true; do sleep 3600; done"],
    volumes: ["./openclaw.config.json:/etc/openclaw/config.json:ro"],
    networks: ["openclaw_net"],
    depends_on: ["dns_allowlist"],
    dns: [OPENCLAW_DNS_RESOLVER_IP]
  };

  if (profile.openclaw.webui.enabled) {
    openclawService.ports = ["127.0.0.1:3000:3000"];
  }

  const compose = {
    name: `openclaw-${profileName}`,
    services: {
      dns_allowlist: dnsAllowlistService,
      openclaw: openclawService
    },
    networks: {
      openclaw_net: {
        name: "openclaw_net",
        driver: "bridge",
        ipam: {
          config: [{ subnet: OPENCLAW_NETWORK_SUBNET }]
        }
      }
    }
  };

  return YAML.stringify(compose);
}

function buildReadme(profileName: string, profile: ProfileConfig): string {
  const allowlist = normalizedAllowlist(profile);
  const allowedDomainExample = allowlist[0] ?? "localhost";
  const blockedDomainExample = allowlist.includes("example.com") ? "iana.org" : "example.com";
  const webUiStatus = profile.openclaw.webui.enabled
    ? "Enabled and bound to localhost only (`127.0.0.1:3000`)."
    : "Disabled by default (no public port exposure).";

  return `# ${profileName} deployment output

This folder is generated by \`ocs install --profile ${profileName}\`.

## Files
- \`docker-compose.yml\` Compose definition with dedicated network \`openclaw_net\`
- \`openclaw.config.json\` Normalized OpenClaw config rendered from profile input
- \`dnsmasq.conf\` DNS allowlist resolver configuration for \`dns_allowlist\`

## Run
\`\`\`bash
docker compose up -d
\`\`\`

## DNS allowlist
- \`dns_allowlist\` is enabled by default for all profiles.
- \`openclaw\` only uses resolver \`${OPENCLAW_DNS_RESOLVER_IP}\`.
- Allowed domains: ${allowlist.length > 0 ? allowlist.map((domain) => `\`${domain}\``).join(", ") : "(none)"}

Validation commands:

\`\`\`bash
docker compose exec -T openclaw nslookup ${allowedDomainExample}
docker compose exec -T openclaw nslookup ${blockedDomainExample}
\`\`\`

Expected: allowlisted lookup succeeds; non-allowlisted lookup fails.

## Web UI exposure
${webUiStatus}

To enable Web UI access for local machine only, set:

\`\`\`yaml
openclaw:
  webui:
    enabled: true
\`\`\`

Then re-run:

\`\`\`bash
node dist/ocs.js install --profile ${profileName}
\`\`\`
`;
}

export function writeInstallArtifacts(profileName: string, profile: ProfileConfig): string {
  const outDir = path.resolve(process.cwd(), "out", profileName);

  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "docker-compose.yml"), buildCompose(profileName, profile), "utf8");
  fs.writeFileSync(path.join(outDir, "openclaw.config.json"), `${JSON.stringify(profile, null, 2)}\n`, "utf8");
  fs.writeFileSync(path.join(outDir, "dnsmasq.conf"), buildDnsmasqConfig(profile), "utf8");
  fs.writeFileSync(path.join(outDir, "README.md"), buildReadme(profileName, profile), "utf8");

  return outDir;
}
